### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by vinshou** [gmanic/daly_bms_bt#4]
Hello, 

I have this problem: 

INFO     [daly_bms_bluetooth.py:46] Bluetooth connecting...
INFO     [daly_bms_bluetooth.py:52] Bluetooth connected
INFO     [daly_bms_bluetooth.py:113] did not receive 13 or 26 bytes, not implemented bytes: 78
WARNING  [daly_bms_bluetooth.py:134] Timeout while waiting for 95 response
INFO     [daly_bms_bluetooth.py:113] did not receive 13 or 26 bytes, not implemented bytes: 78
WARNING  [daly_bms_bluetooth.py:134] Timeout while waiting for 95 response
INFO     [daly_bms_bluetooth.py:113] did not receive 13 or 26 bytes, not implemented bytes: 78
WARNING  [daly_bms_bluetooth.py:134] Timeout while waiting for 95 response
ERROR    [daly_bms_bluetooth.py:77] 95 failed after 3 tries
ERROR    [base_events.py:1738] Task exception was never retrieved
future: <Task finished name='Task-1' coro=<main() done, defined at /home/vincent/DALYBMS/daly_bms_bt/daly_bms_bt.py:123> exception=TypeError("_read_request() got an unexpected keyword argument 'return_list'")>
Traceback (most recent call last):
  File "/home/vincent/DALYBMS/daly_bms_bt/daly_bms_bt.py", line 134, in main
    await con._data_point("CellVoltages", await con.bt_bms.get_cell_voltages())
  File "/home/vincent/DALYBMS/daly_bms_bt/modules/daly_bms_bluetooth.py", line 188, in get_cell_voltages
    return super().get_cell_voltages(response_data=response_data)
  File "/home/vincent/DALYBMS/daly_bms_bt/modules/daly_bms.py", line 281, in get_cell_voltages
    response_data = self._read_request("95", max_responses=max_responses, return_list=True)
TypeError: _read_request() got an unexpected keyword argument 'return_list'

Can you help me ?

**Comment by gmanic** [comment]
Unfortunately, I can't. I stopped working on the repo.
